#!/bin/bash
set -e
die() { echo -e "\e[1m$*\e[0m" >&2; exit 1; }
[ "$(dirname "$(realpath "$(which "$0")")")" == "$(pwd)" ] || die "$0 Must run from own directory"

image=docker.pkg.github.com/svenssonaxel/diff-format/diff-format-tester:latest

docker-run() {
    if [ -t 1 ]; then
        docker run -t "$@"
    else
        docker run "$@"
    fi
}

build-container() {
    docker build -t $image docker
}

run-tests() {
    docker-run -v "$(pwd):/home/user/diff-format:ro" -w /home/user/diff-format/tests $image ./run-tests
}

lint-scripts() {
    docker-run -v "$(pwd):/home/user/diff-format" -w /home/user/diff-format $image shellcheck script implementations/git/* make-img/check-img
}

check-img() {
    docker-run -v "$(pwd):/home/user/diff-format:ro" -w /home/user/diff-format/make-img $image ./check-img
}

build-and-validate() {
    build-container
    run-tests
    lint-scripts
    check-img
}

update-img() {
    rm -rf img/
    docker-run -v "$(pwd):/home/user/diff-format" -w /home/user/diff-format/make-img $image make -j
}

CMD="$1"

case "$CMD" in
    build-container|run-tests|lint-scripts|check-img|build-and-validate|update-img)
        $CMD
        ;;
    *)
        if [[ -z "$CMD" ]]; then
            cat <<EOF
Usage:
  ./script build-container              # Build container for running tests
  ./script run-tests                    # Use container to run tests
  ./script lint-scripts                 # Use container to lint shell scripts
  ./script check-img                    # Use container to check that img/ is up to date
  ./script build-and-validate           # Run all of the above in order
  ./script update-img                   # Use container to update img/
EOF
            exit 0
        else
            echo "Unknown command: $CMD"
            exit 1
        fi
        ;;
esac
