#!/usr/bin/env python3
import contextlib, os, re, sys, tempfile, unittest

def m(pattern, string):
    match = re.match(pattern, string, re.DOTALL)
    if not match:
        return None
    if(match.group(0) != string):
        die(f'Pattern /${pattern}/ matched only part of string')
    ret = []
    for index in range((match.lastindex or 0)+1):
        ret.append(match.group(index))
    return ret

def die(reason):
    sys.stderr.write(reason+'\n')
    sys.exit(1)

# Polyfill
if not 'waitstatus_to_exitcode' in dir(os):
    def waitstatus_to_exitcode(sts):
        if os.WIFSIGNALED(sts):
            return -os.WTERMSIG(sts)
        else:
            assert os.WIFEXITED(sts), "Status is {:n}".format(sts)
            return os.WEXITSTATUS(sts)
    os.waitstatus_to_exitcode = waitstatus_to_exitcode

@contextlib.contextmanager
def inDir(dirName):
    olddir = os.getcwd()
    os.chdir(dirName)
    try:
        yield
    finally:
        os.chdir(olddir)

@contextlib.contextmanager
def filesInTmpDir(files):
    with tempfile.TemporaryDirectory() as tempdir:
        ec = os.waitstatus_to_exitcode(os.system(f'cp -pr -- {" ".join(files)} {tempdir}'))
        if not ec==0:
            die('Failed to copy files into temporary directory')
        with inDir(tempdir):
            yield

implementationsOf={}
def findImplementations():
    with inDir(os.path.join('..', 'implementations')):
        for dirName in os.listdir():
            with inDir(dirName):
                path=os.getcwd()
                for fileName in os.listdir():
                    implementationsOf[fileName] = [*(implementationsOf[fileName] if fileName in implementationsOf else []), os.path.join(path, fileName)]

def red(text):
    if(sys.stdout.isatty()):
        return f'\x1b[31m{text}\x1b[0m'
    else:
        return text

class TestAll(unittest.TestCase):

    # Count asserts

    _assertCount=0

    def assertEqual(self, expected, actual):
        self._assertCount+=1
        super().assertEqual(expected, actual)

    # Pretty nested tests

    _nestTestMsgs=[]

    @contextlib.contextmanager
    def nestTest(self, msg):
        self._nestTestMsgs.append(msg)
        msgs=[*self._nestTestMsgs] # Defensive copy
        print(f"{' │' * (len(msgs) - 1)} ╭╴{msg}")
        done=False
        try:
            with self.subTest("Nested test", path=msgs):
                yield
                print(f"{' │' * (len(msgs) - 1)} ╰╴Done")
                done=True
        finally:
            if not done:
                print(f"{' │' * (len(msgs) - 1)} ╰╴{red('NOT SUCCESSFUL!')} TEST PATH:")
                for m in msgs:
                    print(f"{' │' * (len(msgs) - 1)}   ✦ {m}")
                if(sys.stdin.buffer.isatty() and sys.stdout.buffer.isatty()):
                    print(f"{' │' * (len(msgs) - 1)}   ➔ Current dir: {os.getcwd()}")
                    print("pausing…")
                    sys.stdin.readline()
            self._nestTestMsgs.pop()

    # Will be executed by unittest.main

    def test_all(self):
        testdirs=os.listdir()
        testdirs.sort()
        for testdir in testdirs:
            if re.match('^[0-9]{3}$', testdir):
                with self.nestTest(f'Tests in directory {testdir}'):
                    with inDir(testdir):
                        self.doTestThisDir()
        print(f'(asserts={self._assertCount})')

    # Run all tests in one directory

    def doTestThisDir(self):
        contentfiles = []
        files=os.listdir()
        files.sort()
        for filename in files:
            match = m('^[0-9]+-([a-z])-([a-z])\.(.*)', filename)
            if(match):
                with self.nestTest(f'Test file {filename}'):
                    v1 = match[1]
                    v2 = match[2]
                    testtype = match[3]
                    if(testtype=='unified.diff'):
                        self.doTestUnifiedDiff(filename, v1, v2)
                    elif(testtype=='hintful.diff'):
                        self.doTestHintfulDiff(filename, v1, v2)
                    elif(testtype=='invalid.unified.diff'):
                        self.doTestInvalidUnifiedDiff(filename)
                    elif(testtype=='invalid.hintful.diff'):
                        self.doTestInvalidHintfulDiff(filename)
                    else:
                        self.fail(f"Don't know what to do with file {filename}")
                continue
            match = m('^([a-z])$', filename)
            if(match):
                for otherfile in contentfiles:
                    with self.nestTest(f'Test content files {otherfile} and {filename}'):
                        self.doTestContentFiles(otherfile, filename)
                contentfiles.append(filename)
                continue
            self.fail(f"Don't know what to do with file {filename}")

    # Functions for testing

    def doTestUnifiedDiff(self, diffFile, v1, v2):
        self.doTestUnifiedDiffForwardPatch(diffFile, v1, v2)
        for validateUnifiedDiff in implementationsOf['validate-unified-diff']:
            with self.nestTest(f'Validate unified diff using {validateUnifiedDiff}'):
                self.sh(f'cat {diffFile} | {validateUnifiedDiff}')
        if not m('^.*converted-to\.unified\.diff.*$', diffFile):
            for convertUnifiedDiffToHintfulDiff in implementationsOf['convert-unified-diff-to-hintful-diff']:
                with self.nestTest(f'Convert to hintful using {convertUnifiedDiffToHintfulDiff}'):
                    with filesInTmpDir([diffFile, v1, v2]):
                        self.sh(f'cat {diffFile} | {convertUnifiedDiffToHintfulDiff} > {diffFile}.converted-to.hintful.diff')
                        self.doTestHintfulDiff(f'{diffFile}.converted-to.hintful.diff', v1, v2)
        if not m('^.*\.reversed$', diffFile):
            for reverseUnifiedDiff in implementationsOf['reverse-unified-diff']:
                with self.nestTest(f'Reverse unified diff using {reverseUnifiedDiff}'):
                    with filesInTmpDir([diffFile, v1, v2]):
                        self.sh(f'cat {diffFile} | {reverseUnifiedDiff} > {diffFile}.reversed')
                        with self.nestTest(f'Double reverse is noop'):
                            with filesInTmpDir([diffFile, f'{diffFile}.reversed', v1, v2]):
                                self.assertNotSame(diffFile, f'{diffFile}.reversed')
                                self.sh(f'cat {diffFile}.reversed | {reverseUnifiedDiff} > {diffFile}.reversed.reversed')
                                self.doTestUnifiedDiffForwardPatch(f'{diffFile}.reversed.reversed', v1, v2)
                        with self.nestTest(f'Use reverse diff file as diff file'):
                            self.doTestUnifiedDiff(f'{diffFile}.reversed', v2, v1)
        with self.nestTest(f'Unified diff should be invalid as hintful diff'):
            self.doTestInvalidHintfulDiff(diffFile)
        if(not self.shBool(f"grep -ERq '^\\\\ No newline' {diffFile}")):
            for [explanation, PRE] in [
                    ['Add CR', r's@\n@\r\n@'],
                    ['Add CRCR', r's@\n@\r\r\n@'],
                    ['Remove CR', r's@\r\n@\n@'],
                    ['Remove CR twice', r's@\r\n@\n@;s@\r\n@\n@'],
            ]:
                with self.nestTest(f'Convert newline: {explanation}'):
                    with filesInTmpDir([diffFile, v1, v2]):
                        newDiffFile=f'{diffFile}.newlineconverted.diff'
                        self.sh(f'cp {diffFile} {newDiffFile}')
                        self.mapFiles(f"perl -pe '{PRE}'", [newDiffFile, v1, v2])
                        self.doTestUnifiedDiffForwardPatch(newDiffFile, v1, v2)

    def doTestHintfulDiff(self, diffFile, v1, v2):
        self.doTestHintfulDiffForwardPatch(diffFile, v1, v2)
        for validateHintfulDiff in implementationsOf['validate-hintful-diff']:
            with self.nestTest(f'Validate hintful diff using {validateHintfulDiff}'):
                self.sh(f'cat {diffFile} | {validateHintfulDiff}')
        if not m('^.*converted-to\.hintful\.diff.*$', diffFile):
            for convertHintfulDiffToUnifiedDiff in implementationsOf['convert-hintful-diff-to-unified-diff']:
                with self.nestTest(f'Convert to unified using {convertHintfulDiffToUnifiedDiff}'):
                    with filesInTmpDir([diffFile, v1, v2]):
                        self.sh(f'cat {diffFile} | {convertHintfulDiffToUnifiedDiff} > {diffFile}.converted-to.unified.diff')
                        self.doTestUnifiedDiff(f'{diffFile}.converted-to.unified.diff', v1, v2)
        if not m('^.*\.reversed$', diffFile):
            for reverseHintfulDiff in implementationsOf['reverse-hintful-diff']:
                with self.nestTest(f'Reverse hintful diff using {reverseHintfulDiff}'):
                    with filesInTmpDir([diffFile, v1, v2]):
                        self.sh(f'cat {diffFile} | {reverseHintfulDiff} > {diffFile}.reversed')
                        with self.nestTest(f'Double reverse is noop'):
                            with filesInTmpDir([diffFile, f'{diffFile}.reversed', v1, v2]):
                                self.assertNotSame(diffFile, f'{diffFile}.reversed')
                                self.sh(f'cat {diffFile}.reversed | {reverseHintfulDiff} > {diffFile}.reversed.reversed')
                                self.doTestHintfulDiffForwardPatch(f'{diffFile}.reversed.reversed', v1, v2)
                        with self.nestTest(f'Use reverse diff file as diff file'):
                            self.doTestHintfulDiff(f'{diffFile}.reversed', v2, v1)
        with self.nestTest(f'Hintful diff should be invalid as unified diff'):
            self.doTestInvalidUnifiedDiff(diffFile)
        for [explanation, PRE] in [
                ['Add CR', r's@\n@\r\n@'],
                ['Add CRCR', r's@\n@\r\r\n@'],
                ['Remove CR', r's@\r\n@\n@'],
                ['Remove CR twice', r's@\r\n@\n@;s@\r\n@\n@'],
        ]:
            with self.nestTest(f'Convert newline: {explanation}'):
                with filesInTmpDir([diffFile, v1, v2]):
                    newDiffFile=f'{diffFile}.newlineconverted.diff'
                    self.sh(f'cp {diffFile} {newDiffFile}')
                    self.mapFiles(f"perl -pe '{PRE}'", [newDiffFile, v1, v2])
                    self.doTestHintfulDiffForwardPatch(newDiffFile, v1, v2)

    def doTestUnifiedDiffForwardPatch(self, diffFile, v1, v2):
        with self.nestTest(f'Test unified forward patch'):
            with filesInTmpDir([diffFile, v1, v2]):
                self.assertNotSame(v1, v2)
                self.sh(f'cp -pr {v1} {v1}.bu')
                self.assertSame(v1, f'{v1}.bu')
                for patchUnified in implementationsOf['patch-unified']:
                    with self.nestTest(f'Patch unified using {patchUnified}'):
                        with filesInTmpDir([diffFile, v1, v2, f'{v1}.bu']):
                            self.sh(f'{patchUnified} {v1} < {diffFile}')
                            self.assertSame(v1, v2)
                            self.assertNotSame(v1, f'{v1}.bu')

    def doTestHintfulDiffForwardPatch(self, diffFile, v1, v2):
        with filesInTmpDir([diffFile, v1, v2]):
            convertHintfulDiffToUnifiedDiff = implementationsOf['convert-hintful-diff-to-unified-diff'][0]
            with self.nestTest(f'Convert to unified using {convertHintfulDiffToUnifiedDiff}'):
                self.sh(f'cat {diffFile} | {convertHintfulDiffToUnifiedDiff} > {diffFile}.converted-to.unified.diff')
                self.doTestUnifiedDiffForwardPatch(f'{diffFile}.converted-to.unified.diff', v1, v2)

    def doTestInvalidUnifiedDiff(self, diffFile):
        for validateUnifiedDiff in implementationsOf['validate-unified-diff']:
            with self.nestTest(f'Make sure unified diff is invalid using {validateUnifiedDiff}'):
                self.sh(f'cat {diffFile} | {validateUnifiedDiff} 2>/dev/null', 1)

    def doTestInvalidHintfulDiff(self, diffFile):
        for validateHintfulDiff in implementationsOf['validate-hintful-diff']:
            with self.nestTest(f'Make sure hintful diff is invalid using {validateHintfulDiff}'):
                self.sh(f'cat {diffFile} | {validateHintfulDiff} 2>/dev/null', 1)

    def doTestContentFiles(self, v1, v2):
        for diffUnified in implementationsOf['diff-unified']:
            with self.nestTest(f'Create unified diff using {diffUnified}'):
                with filesInTmpDir([v1, v2]):
                    self.sh(f'{diffUnified} {v1} {v2} > generated_diff-{v1}-{v2}-unified.diff', 1)
                    self.doTestUnifiedDiff(f'generated_diff-{v1}-{v2}-unified.diff', v1, v2)

    # Utility

    def assertSame(self, v1, v2):
        self.sh(f'diff -u -r {v1} {v2}', 0)

    def assertNotSame(self, v1, v2):
        self.sh(f'diff -u -r {v1} {v2} > /dev/null', 1)

    def sh(self, cmd, expectedExitCode=0):
        self.assertEqual(expectedExitCode, os.waitstatus_to_exitcode(os.system(f'set -e; {cmd}')))

    def shBool(self, cmd):
        ec = os.waitstatus_to_exitcode(os.system(f'set -e; {cmd}'))
        assert ec in [0, 1]
        return {0: True, 1: False}[ec]

    def mapFiles(self, cmd, files):
        for filename in files:
            if(os.path.isfile(filename)):
                self.sh(f'cat {filename} | {cmd} > {filename}.tmp.processing; mv {filename}.tmp.processing {filename};')
            elif(os.path.isdir(filename)):
                files2 = os.listdir(filename)
                with inDir(filename):
                    self.mapFiles(cmd, files2)
            else:
                die(f'Cannot map file node {os.path.join(os.getcwd(),filename)}')

if m('^.*[ !"#$&\'()*+;<>?\\^`{|}~].*$', os.getcwd()):
    die(f'Running from a weird path.')
findImplementations()
if __name__ == '__main__':
    unittest.main()
