#!/usr/bin/env bash
set -e
[ -e "$1"/.git ] && exit 2
[ -e "$2"/.git ] && exit 2
(
    cd "$1"
    git init
    git add .
    git commit -m 1
)>/dev/null
mv "$1"/.git "$2"/
(
    cd "$2"
    git add .
    git commit -m 2
)>/dev/null
cd "$2"
if git diff -a --exit-code HEAD^; then
    exit 0
else
    rm -rf .git
    exit 1
fi
